all:  keha kokku

kokku :
	cat DBparingud.algus \
		võrdlesõna_etvro.py \
		võrdlesõna_vroet.py \
		erindid_etvro.py \
		erindid_vroet.py \
		leialõpuliited_et.py \
		leialõpuliited_vro.py \
		genereerisõna_etvro.py \
		uuendatõlkesõna.py \
		sisestatõlkesõnadesse.py \
		vormikutestsõnadesse.py \
		ennetõlget.py \
		tõlgilõpuliited_etvro.py \
		valiparalleeltõlge.py \
		uuendalõpuliiteid.py \
		tüvekontra_vro.py \
		DBparingud.lõpp > dbparingud.py

keha : võrdlesõna_etvro võrdlesõna_vroet erindid_etvro erindid_vroet leialõpuliited_et leialõpuliited_vro genereerisõna_etvro uuendatõlkesõna vormikutestsõnadesse ennetõlget valiparalleeltõlge sisestatõlkesõnadesse tõlgilõpuliited_etvro tüvekontra_vro uuendalõpuliiteid

võrdlesõna_etvro :
		cat \
			võrdlesõna_etvro.algus \
			võrdlesõna_etvro.sql \
			võrdlesõna_etvro.lõpp \
			> \
			võrdlesõna_etvro.py

võrdlesõna_vroet :
		cat \
			võrdlesõna_vroet.algus \
			võrdlesõna_vroet.sql \
			võrdlesõna_vroet.lõpp \
			> \
			võrdlesõna_vroet.py

erindid_etvro :
		cat \
			erindid_etvro.algus \
			erindid_etvro.sql \
			erindid_etvro.lõpp \
			> \
			erindid_etvro.py

erindid_vroet :
		cat \
			erindid_vroet.algus \
			erindid_vroet.sql \
			erindid_vroet.lõpp \
			> \
			erindid_vroet.py

leialõpuliited_et :
		cat \
			leialõpuliited_et.algus \
			leialõpuliited_et.sql \
			leialõpuliited_et.lõpp \
			> \
			leialõpuliited_et.py

leialõpuliited_vro :
		cat \
			leialõpuliited_vro.algus \
			leialõpuliited_vro.sql \
			leialõpuliited_vro.lõpp \
			> \
			leialõpuliited_vro.py

genereerisõna_etvro :
		cat \
			genereerisõna_etvro.algus \
			genereerisõna_etvro.sql \
			genereerisõna_etvro.lõpp \
			>  \
			genereerisõna_etvro.py

uuendatõlkesõna :
		cat \
			uuendatõlkesõna.algus \
			uuendatõlkesõna.sql \
			uuendatõlkesõna.lõpp \
			>  \
			uuendatõlkesõna.py

ennetõlget :
		cat \
			ennetõlget.algus \
			ennetõlget.sql \
			ennetõlget.lõpp \
			>  \
			ennetõlget.py

tõlgilõpuliited_etvro :
		cat \
			tõlgilõpuliited_etvro.algus \
			tõlgilõpuliited_etvro.sql \
			tõlgilõpuliited_etvro.lõpp \
			>  \
			tõlgilõpuliited_etvro.py

vormikutestsõnadesse :
		cat \
			vormikutestsõnadesse.algus \
			vormikutestsõnadesse.sql \
			vormikutestsõnadesse.lõpp \
			>  \
			vormikutestsõnadesse.py

valiparalleeltõlge :
		cat \
			valiparalleeltõlge.algus \
			valiparalleeltõlge.sql \
			valiparalleeltõlge.lõpp \
			>  \
			valiparalleeltõlge.py

sisestatõlkesõnadesse :
		cat \
			sisestatõlkesõnadesse.algus \
			sisestatõlkesõnadesse.sql \
			sisestatõlkesõnadesse.lõpp \
			>  \
			sisestatõlkesõnadesse.py

tüvekontra_vro :
		cat \
			tüvekontra_vro.algus \
			tüvekontra_vro.sql \
			tüvekontra_vro.lõpp \
			>  \
			tüvekontra_vro.py

uuendalõpuliiteid :
		cat \
			uuendalõpuliiteid.algus \
			uuendalõpuliiteid.sql \
			uuendalõpuliiteid.lõpp \
			>  \
			uuendalõpuliiteid.py


clean :
	rm \
		võrdlesõna_etvro.py \
		võrdlesõna_vroet.py \
		erindid_etvro.py \
		erindid_vroet.py \
		leialõpuliited_et.py \
		leialõpuliited_vro.py \
		genereerisõna_etvro.py \
		uuendatõlkesõna.py \
		sisestatõlkesõnadesse.py \
		valiparalleeltõlge.py \
		vormikutestsõnadesse.py \
		tõlgilõpuliited_etvro.py \
		ennetõlget.py \
		uuendalõpuliiteid.py \
		tüvekontra_vro.py \
